version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  mongodb:
    networks:
      - internal
    labels:
      - traefik.enable=false
  server:
    labels:
      - traefik.backend=rps-game
      - traefik.frontend.rule=Host:rps-game.juandastic.co
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy